global using mark.davison.common.persistence;
global using mark.davison.common.Repository;
global using mark.davison.common.server.abstractions.Health;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.Extensions.DependencyInjection;
global using System.Net;
global using System.Text;
global using System.Text.Json;
